import type { Metadata } from "next";
import "./globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";
import { SidebarDemo } from "@/components/MainSidebar";


export const metadata: Metadata = {
  title: "Mohit Uniyal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SidebarProvider>
            <SidebarDemo>
              {children}
            </SidebarDemo>
        </SidebarProvider>
      </body>
    </html>
  );
}
