import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { DesktopSidebar, SidebarProvider } from "@/components/ui/sidebar";
import { SidebarDemo } from "@/components/MainSidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Mohit Uniyal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SidebarProvider>
            <SidebarDemo>
              {children}
            </SidebarDemo>
        </SidebarProvider>
      </body>
    </html>
  );
}
